### ISSUE TITLE
Observed memory leak in Erlang driver of re2

### ISSUE THREAD

**Issue by matehat** [google/re2#120]
The following issue/PR is reporting a memory leak that seems to come from re2. It is not clear at this time whether it's from re2 itself, or the erlang driver for it, by @tuncer: https://github.com/tuncer/re2/.

https://github.com/matehat/cqerl/pull/115

The issue contains a stacktrace and some useful information on how to reproduce it consistently.

**Comment by tuncer** [comment]
@matehat, thanks for the report.

What version of the bindings and re2 code have you used? If you want to try a different re2 revision than the current default (`2016-06-01`), you can override it with the env var `RE2_REV`. I didn't update the default of the locally fetched (and built) re2 revision yet due to #102. If you're using something else than g++ >=6 as your CXX, then you can try a newer re2 version.

First, a couple explanations for developers unfamiliar with Erlang:
* NIF is one of the methods for Erlang to interface with native code, in this case linking the native code dynamically at runtime in the same process as the VM and avoiding message passing.
* `re2:compile/2` refers to the function `compile` with arity `2` in the Erlang module `re2`.
* `enif_` is the Erlang NIF API's prefix.
* `re2_nif` is the C++ code that implements the re2 bindings for Erlang with the NIF method.
* Erlang NIF resource objects are opaque variables on the Erlang VM side and managed in C to provide stateful bindings. The Erlang code basically treats it like a handle that's just passed around.
* When I say "Erlang side" I mean when the VM executes Erlang code and is not executing the native (C, C++) code.

---

To analyze the issue, let me explain how re2_nif resource handling works:

### stateful

If you compile a regex via `re2:compile/2`, then you get an opaque Erlang NIF resource object which owns and holds on to a RE2 object. Once the Erlang VM decides the resource object should be released, the cleanup function in `re2_nif.cpp` is called. The resource object is for use in `match` and `replace` in place of a literal regex.

### stateless
If you pass a regex string (instead of a compiled regex resource), then inside the handler (`match`, `replace`) an RE2 object is constructed and freed immediately after use, before we return to the Erlang side.

In either case the `autohandle` class is used to either hold on to or release the RE2 object on scope exit.

---

If the Erlang code compiles regexes, and the Erlang variables are never released, then it's a potential leak in the Erlang code, just like one can leak memory with Erlang bit syntax.

If however you `match` or `replace` repeatedly with a literal regex in a loop, and RE2 objects are never released, then that's a bug in the bindings.

Also, instead of `new`/`delete` or `malloc`/`free`, `re2_nif` uses `enif_alloc`/`enif_free` via C++'s placement new feature. This is done in order to use the same memory management routines as the rest of the Erlang VM.

**Comment by tuncer** [comment]
I'll try to analyze it this weekend.

**Comment by bernardd** [comment]
For reference, the only two regexs (regecies?) that could be involved are:

`'*(\\?|:\\w+)'*(?:(?:[^\"]*\"[^\"]*\")*[^\"]*$)`
and
`^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})(?::([0-9]{1,5}))?$`

Escaping is as it appears in the code.

**Comment by bernardd** [comment]
On looking closer at the code, if it is one of those regexes causing it, it's most likely to be the first one - the second one is only used when reading the app's config, so is probably only called a small number of times at startup.

**Comment by junyer** [comment]
19 days ago, @bernardd wrote:

> It would be very useful to have a minimal replication case just using re2 - if it's leaking as badly as you say, it should be a pretty simple matter of setting up a loop doing regex matches and watching the memory use explode.

Drawing inspiration from that and also considering his comments today, I wrote a test case that just runs the following code in a loop:

```
    StringPiece sp1;
    RE2::FullMatch("asdf", "'*(\\?|:\\w+)'*(?:(?:[^\"]*\"[^\"]*\")*[^\"]*$)", &sp1);
    RE2::PartialMatch("asdf", "'*(\\?|:\\w+)'*(?:(?:[^\"]*\"[^\"]*\")*[^\"]*$)", &sp1);
```

Note that the regular expression will be constructed (i.e. parsed and compiled), executed and destructed twice per iteration.

I ran the test case three times with heap checking enabled: 1000 iterations, 10000 iterations, 100000 iterations. No leaks were found.

**Comment by junyer** [comment]
Looking closer, it appears that `NAMED_BINDINGS_RE` is compiled once whereas `IPV4_RE` is compiled every time. Furthermore, all of the leaks reported seem to indict the code path in `re2_match()` that compiles a "temporary" `RE2` object.

**Comment by guitarmind** [comment]
@tuncer @bernardd @junyer 

Thanks a lot for the follow-ups, here are the versions of re2 and re2 NIF that I'm using:
```
re2: latest, built every time by [tuncer/re2](https://github.com/tuncer/re2/blob/master/c_src/build_deps.sh#L16)
re2 NIF:  1.4.0  [matehat/re2](https://github.com/matehat/re2/commits/master)
c++: 6.2.1
```

**Running Environments**
```
- Ubuntu 14.04 LTS 64-bit (a VM of 2 vCPU and 4GB RAM)
- Alpine Linux 3.4 64-bit (a Docker container of 1 vCPU and 1GB RAM)
```

After removing re2 NIF the service has been running without memory leak for several weeks.

**Comment by junyer** [comment]
We should figure out where the leak is, obviously, but I would suggest replacing `IPV4_RE` with a host:port parser that doesn't use regular expressions. If it helps, https://github.com/erlang/otp/blob/master/lib/inets/src/http_lib/http_uri.erl#L188-L196 is the best example in Erlang that I have found so far.

**Comment by tuncer** [comment]
A leak might have been introduced when the code was converted to use placement new.
Looking into the possibility of `~RE2()` not being invoked, and given the recently introduced C++11 requirement, whether unique_ptr/shared_ptr can be used instead of the custom class.

**Comment by tuncer** [comment]
Yep, invoking RE2's destructor got lost during the conversion to use enif_alloc/enif_free. The only explanation for this having been hidden for so long is that heavy callers use compiled regex objects, because the resource cleanup function has been invoking the destructor.

**Comment by tuncer** [comment]
See https://github.com/tuncer/re2/issues/17. I think we can close this ticket. If one of you has experience with C++ placement syntax in combination with unique_ptr, I'd appreciate implementation advice in that ticket. It's not a common thing to do, so getting this right with C++11 features might take a while. In the meantime, I'm looking into a minimally invasive short-term fix.

**Comment by junyer** [comment]
Many thanks, @tuncer. I'll follow up over there.
