### ISSUE TITLE
StringPiece problems with null data

### ISSUE THREAD

**Issue by junyer** [google/re2#129]
@H2CO3 commented on `StringPiece::operator==()`:

> doesn't this have undefined behavior when `x` and `y` are empty and at least one of them constructed with a `NULL` buffer? In that case, `x.size() == y.size()` (== 0), and so `memcmp` is called with one or two `NULL` arguments. A similar problem is present in `operator<`.

**Comment by junyer** [comment]
http://en.cppreference.com/w/c/string/byte/memcmp says: "The behavior is undefined if access occurs beyond the end of either object pointed to by lhs and rhs. The behavior is undefined if either lhs or rhs is a null pointer."

It does appear that these functions (plus a couple of others) mistakenly rely on `memcmp(3)` to return 0.

**Comment by H2CO3** [comment]
This kind of problem arises when computing the end iterator as well. There, `return data_ + size_` means that if `data_` is `NULL`, then we are performing pointer arithmetic on a null pointer, which is also undefined behavior. I propose replacing null pointers in constructors by an empty string literal (`""`) instead. String literals have static storage duration, so this should be fine.

**Comment by junyer** [comment]
The difference between a null `StringPiece` and an empty `StringPiece` does matter, so removing support for the former isn't feasible.

Interestingly, `std::string_view` has the same problem with `end()` in [libstdc++](https://gcc.gnu.org/viewcvs/gcc/trunk/libstdc%2B%2B-v3/include/std/string_view?view=markup) and [libc++](http://llvm.org/svn/llvm-project/libcxx/trunk/include/string_view). Perhaps calling `end()` on a null `std::string_view` is undefined behaviour?

I'm following up with folks at Google regarding the `memcmp(3)` issue.

**Comment by H2CO3** [comment]
Er, I can't find anywhere in the `std::string_view` TS that it can differentiate between an empty and a "null" object. However, programmers implementing the stdlib have the convenience that they can rely on the behavior of their very compiler, which may opt to define otherwise undefined behavior. (I'm not sure if GCC and Clang define pointer arithmetic on `nullptr`, though.) So in a standard library implementation, this might be less of a concern than inside an external library, of which the code should generally not rely upon compiler internals.

Anyway, back to the topic: wouldn't it be better to replace "null StringPiece"s with an appropriately-typed optional object then? And if not, the UB should still be removed; perhaps the comparison operators could be made null-safe? (I'm aware that this potentially induces a performance penalty.)

**Comment by junyer** [comment]
Just to be clear, I meant "null" in the sense that `data()` returns `nullptr` and `size()` returns 0, but it sounds as though the former isn't guaranteed for the default constructor. Is `nullptr + 0` defined?

**Comment by H2CO3** [comment]
Yes, I meant that as well; what I assumed was that `data()` returning `nullptr` meant "optional" as opposed to `data() != nullptr && size() == 0`, which I thought you meant by "empty".

I have made some research and apparently adding 0 to any pointer is a well-defined operation, so `nullptr + 0` should also be well-defined in this case.
