### ISSUE TITLE
Unable to differentiate between out-of-memory and no-match in RE2::Set::Match

### ISSUE THREAD

**Issue by alexsharoff** [google/re2#136]
I'm trying to handle out-of-memory errors in RE2::Set (increase max_mem, recompile Set and call Match again). The problem is RE2::Set::Match returns 'false' both if no match is found and on out-of-memory.

**Comment by junyer** [comment]
The underlying issue is not that the DFA runs out of memory, but that it runs out of memory twice while handling a given input string. This is a strong signal that the combined regular expression is too unwieldy for `RE2::Set`, so throwing more memory at it is just papering over the problem. Are you able to disclose anything about your use case? Using `FilteredRE2` instead might be the right solution.

**Comment by alexsharoff** [comment]
I have ~100 complex regexps and need to match them as fast as possible. I've tried different approaches and the fastest turned out to be like that:
* Split regexps into sets. Set size varies to obtain maximal performance of all sets combined.
* Match text chunk using sets
* Match the same text with single regexps that were reported by sets

I remember trying out FilteredRE2, but Compile(...) didn't return any useful strings. I suspect it's because there are almost no raw substrings in these regexps, only character classes like \d and \w.

**Comment by junyer** [comment]
Understood. Thanks for confirming that `FilteredRE2` was not suitable.

Given the situation that you described, I think that Hyperscan (https://github.com/01org/hyperscan) would be a much better choice than RE2. Matching hundreds or thousands of regular expressions is their forte. (Ping, @mdb256.)
