### ISSUE TITLE
posix compatibility

### ISSUE THREAD

**Issue by rsc** [google/re2#146]
Per my email, it appears that @lsloan commented on the initial commit, but I can't find it in the web UI so I am creating an issue instead, for a proper reply (issues are better than commit comments anyway). The comment was:

> The lack of POSIX compatibility makes this library less attractive for use. While there are many good reasons to use this library, without POSIX features it's being held back from broader acceptance.

I'm not sure what POSIX features means here. If it means POSIX regexp syntax, that's supported - use RE2::POSIX in the constructor. If it means the C regexp.h header API, that has been written by others. There is a link in the README (and on the main page https://github.com/google/re2) to the C bindings, as well as bindings for other languages. The C bindings are at https://github.com/marcomaggi/cre2/.

**Comment by junyer** [comment]
I believe that they meant POSIX semantics for submatches. https://swtch.com/~rsc/regexp/regexp2.html#posix is relevant here. :)

**Comment by lsloan** [comment]
Thanks for opening the issue, @rsc.  I should have opened an issue instead of adding new comments to the old commits.  As you wrote, it might not be easy to find the comments if they're not part of a code review on an open pull request.

My concern was that the RE2 documentation I've seen didn't explicitly mention compliance with POSIX regular expression specifications.  So I searched through the code for mentions of "posix".  Although it's mentioned in various places, it wasn't clear to me that it added up to compliance.  I believe it does show support for some features of POSIX, though.

What prompted me to leave a comment was [the comment around line 164 of `prog.h`](https://github.com/google/re2/commit/0a38cba1d9dcfbd713141095582597af700f22e9#diff-6200b3452cd965f27b801f3cad7c8626R164).  It seemed to suggest POSIX wasn't supported.

I wasn't sure, though, since I know code comments can get out of date from the code.  My comment was meant to be more of a question about POSIX support than a complaint, feature request, or bug report.

**Comment by rsc** [comment]
The problem is that there are many different possible meanings of POSIX. I identified two above (syntax, C API), and Paul added one more (submatch choice).

What do _you_ mean by POSIX?

**Comment by lsloan** [comment]
I'm not exactly sure what the meaning of POSIX compliance is in terms of the project with which I'd like to use RE2.  Basically, I'd like assurance that the regular expressions I've been using, which work with other POSIX-compliant regex implementations, will work with RE2, too.  Given the definitions mentioned in this issue comment thread, syntax and submatch choice are most like what I have in mind.

I understand there are some regex features RE2 doesn't implement in either POSIX mode or not.  Those unimplemented features seem to be documented and that's OK for now.  I just don't want to worry about differences between how my POSIX regexes are interpreted by RE2 as opposed to other implementations.

**Comment by rsc** [comment]
RE2 certainly supports POSIX syntax and will match if and only if the POSIX engine matches. The submatch boundaries may differ if there is more than one way to draw those boundaries. In practice there usually isn't more than one way; in many of the remaining cases, the two agree. But there are certainly cases where the submatch semantics do differ. 

For example if you search for `(x+)(x+)` in `axxxxxb` then both Perl and POSIX agree that the 5 matched x's break down as `(xxxx)(x)`. But if you search for `(x|xx)(x+)` then Perl breaks it down as `(x)(xxxx)` (choosing the first possible alternative for the `x|xx`) while POSIX breaks it down as `(xx)(xxx)` (choosing the longest choice for the first parens). It's too complex to do POSIX submatch choices efficiently in general, so RE2 doesn't and likely never will. If that's a requirement for your use case then RE2 is inappropriate. But honestly I haven't encountered many systems that need those specific rules. In fact I doubt there are more than a handful of people who truly understand the full implications of the POSIX rules (I may have been one in the past, but am not now, without going back to old notes).

**Comment by lsloan** [comment]
Thanks for the submatch explanation.  That's very helpful.

I have a question about the POSIX syntax, though.  You say it will match iff the POSIX engine matches.  Does that mean it will fall back to another engine if there is no match?  If so, can I specify that RE2 should only use the POSIX one?

**Comment by rsc** [comment]
> You say it will match iff the POSIX engine matches. Does that mean it will fall back to another engine if there is no match? If so, can I specify that RE2 should only use the POSIX one?

I mean that RE2 will agree with any (hypothetical other) POSIX-conforming regexp engine about whether there is a match and exactly where it is in the text. The only possible point of disagreement is how the overall match breaks into submatch.
