### ISSUE TITLE
Is it possible to achieve (?!re) using another regex?

### ISSUE THREAD

**Issue by felpin** [google/re2#188]
Hello,

Looking at the [syntax page](https://github.com/google/re2/wiki/Syntax), I've noticed that `(?!re)` is not yet supported.

I do not know much about regex, so I'm asking here if it is possible to achieve the same result using another regex.

See... I want to use a regex to match anything but "master". Normally I would do `^(?!master).*$`, but I do not know if it is even possible to do that without using `?!`.

Well... Thanks for any help... By the way, if is there a plan to release this feature soon, let me know.

**Comment by junyer** [comment]
For a string literal _**S**_, it is straightforward to construct a regular expression to match everything except _**S**_.

In the case of "master", either `(?:[^m]|m[^a]|ma[^s]|mas[^t]|mast[^e]|maste[^r]|master.).*` (when `RE2::FullMatch()` is used) or `^(?:[^m]|m[^a]|ma[^s]|mas[^t]|mast[^e]|maste[^r]|master.)` (when `RE2::PartialMatch()` is used) should suffice. Note well the use of `master.` so that "master" itself cannot match.
