### ISSUE TITLE
Feature request: Unicode property intersection [\p{Latin}&&\p{Lu}]

### ISSUE THREAD

**Issue by glebm** [google/re2#194]
Java, Ruby, Python, and other languages all support character class union and intersection operators.

Union is already supported for RE2, for example: `[\p{Lu}\p{Lt}]`.

Intersection is not supported yet, for example: `[\p{Latin}&&\p{Lu}]` (uppercase latin letters).

There is currently no way to express the above in RE2 (short of listing all the code points). In engines that support `(?=)`, the example above can be expressed worked around as `(?=\p{Latin})\p{Lu})`.

**Comment by rsc** [comment]
Union is supported because that's the very definition of character classes (and for that matter regular expressions more generally).

If you add intersection inside character classes, you also have to define precedence, provide some kind of grouping for overrides, and so on and so on. We made a conscious decision well over a decade ago not to go down the road that leads to http://unicode.org/reports/tr18/#Subtraction_and_Intersection. The Unicode consortium can make recommendations but we are not obliged to follow them. Similarly, RE2 is not obliged to follow Perl, Python, Java, etc. 

[Java is documented](https://docs.oracle.com/javase/10/docs/api/java/util/regex/Pattern.html) to support `[X&&[Y]]` and for that matter `[X[Y]]`. The suggested syntax would be a breaking change for RE2. Today `[a&&b]` means `[a&b]`; it would change to be unmatchable. Also Java syntax `[abc[def]]` currently parses as the character class `[abc\[def]` followed by literal `]`. Note that Java is not doing the full Unicode recommendation either.

[Ruby appears to do the same](https://ruby-doc.org/core-2.6.1/doc/regexp_rdoc.html#label-Character+Classes) although—as is the norm for Ruby—without any clear specification of the syntax. I don't put much value in trying to match Ruby. Ruby is what Ruby is, and tomorrow it might be different.

I don't see any evidence that Python supports this syntax. The [Python 3 docs say](https://docs.python.org/3/library/re.html#index-12) they are considering it and currently warning about uses that might change in the future.

You didn't mention Perl, but I don't see any evidence that Perl does. `perl -e 'print ("y" =~ /[x&&a-z]/)' reports a match, which it would not if `&&` meant intersection. And https://perldoc.perl.org/perlre.html does not mention `&&` anywhere except a few times as the Perl control flow operator.

In general we've tried to keep RE2 a fixed syntax instead of "evolving with the times" or trying to add feature upon feature. When Perl changed the meaning of `\v` we didn't even change that.

**Comment by BurntSushi** [comment]
Small note: I didn't know this before today, but apparently Perl has it, but it's experimental and does not match the syntax recommended by UTS#18:

```
$ perl -e 'print ("y" =~ /(?[ [x] & [a-z] ])/)'
```

Perl I guess has a completely separate page documenting its character class support. Specifically, using intersection and the like requires opting into its "extended" character class support: https://perldoc.perl.org/perlrecharclass.html#Extended-Bracketed-Character-Classes

**Comment by junyer** [comment]
Someone pointed me to this issue again. It's worth noting that you can often apply De Morgan's laws to do the needful. For example, `\p{Latin}` AND `\p{Lu}` ≡ NOT(`\P{Latin}` OR `\P{Lu}`) ≡ NOT(`[\P{Latin}\P{Lu}]`) ≡ `[^\P{Latin}\P{Lu}]`.
