### ISSUE TITLE
x?

### ISSUE THREAD

**Issue by vstepaniuk** [google/re2#230]
text:
`=HYPERLINK(A2,"link")`

regex:
`\(""?(.*)""?,?.*\)`

match:
`A2,"link"`

expected match:
`A2`

question:
why `,?` is not matched if
https://github.com/google/re2/blob/5fcdf4ad49097668f0f260dbe6b21fa133302f78/doc/syntax.txt#L24

**Comment by junyer** [comment]
Sorry, your example doesn't make sense to me. Specifically, the input string as given won't match the regular expression as given. Please provide a short code snippet that reproduces the problem.

**Comment by vstepaniuk** [comment]
I am using Google Sheets and need to match the first argument in the text formula `=HYPERLINK(A2,"link")`. The double double quotes are to escape double quotes in a quoted string in Google Sheets. Sorry for not changing them.. so the actual regex is `\("?(.*)"?,?.*\)`, and the match is `A2,"link"`, but should have been `A2`

**Comment by junyer** [comment]
The problem here is that the `(.*)` is greedy and doesn't have to give anything back until the `\)`. (Indeed, as things currently stand, you can observe another problem by changing `A2` to `"A2"`.)

I would probably do something like `=REGEXREPLACE(REGEXEXTRACT(A1,"\(([^,)]+)"),"^""|""$","")` for simplicity: extract up to the next delimiter (either comma or right parenthesis) and then remove leading and trailing double quotes.

**Comment by vstepaniuk** [comment]
> The problem here is that the (.*) is greedy and doesn't have to give anything back until the \).

No, according to `x?	zero or one «x», prefer one`, it should give back comma if it is there

**Comment by junyer** [comment]
Unfortunately, your understanding is incorrect. regex101.com has a debugger that visualises how a backtracking regular expression engine would match, so you could use that to confirm what I said.

**Comment by junyer** [comment]
And just to verify with Perl itself:

```
$ echo '=HYPERLINK(A2,"link")' | perl -lpe 'if(/\("?(.*)"?,?.*\)/){$_=$1};'
A2,"link"
$ 
```
