### ISSUE TITLE
Nested quantifiers and submatching rules

### ISSUE THREAD

**Issue by camilstaps** [google/re2#245]
I'm confused by the way re2 handles nested quantifiers (and submatches).

For example, in perl 5.28, the regex `(a*?)*` matches `a` with the empty string and an empty capturing group. On the other hand, re2 matches it as `a` with `a` in the capturing group. I don't see what rule forces the `a` to be matched. (JavaScript and Go behave like re2.)

Are the semantics in situations like this well-defined? Is there a description of those semantics available somewhere?

**Comment by junyer** [comment]
It's not that RE2 applies some arbitrary rule in this particular situation. It's just that execution works that way. But that's not much of an explanation, so let's work through your example. :)

Here's the bytecode for `(a*?)*`:

```
3+ capture 2 -> 5
4. match! 0
5+ capture 3 -> 3
6. byte [61-61] 0 -> 5
```

- The `*` is greedy, which is why instructions 3 and 4 are in that order: matching `(a*?)` has **_higher_** priority than not matching it.
- The `*?` is non-greedy, which is why instructions 5 and 6 are in that order: matching `a` has **_lower_** priority than not matching it.

Here's how NFA execution works:
_Note: `(s,e)` denotes the bounds of `$1`; **bold** denotes a thread to be stepped._

- At input position 0:
  - thread `(?,?)` is created and reaches `(?,?)` at 3, `(0,?)` at 5, **`(0,?)` at 6**, **`(?,?)` at 4**.
- At input position 1:
  - thread `(0,?)` at 6 is stepped and reaches `(0,?)` at 5, `(0,1)` at 3, **`(0,1)` at 4**, **`(0,?)` at 6**; and
  - thread `(?,?)` at 4 is stepped and matches.
- Finally:
  - thread `(0,1)` at 4 is stepped and matches; and
  - thread `(0,?)` at 6 is terminated.

Hence, `$1` is `(0,1)` because that's the best match that's recorded. (Just to be clear, "best" is a straightforward matter of thread priority.)

Note that https://swtch.com/~rsc/regexp/regexp3.html#caveats says:

> If the regexp contains a repetition of an empty string, like `(a*)+`, then PCRE will treat the reptition sequence as ending with an empty string, while RE2 does not. Specifically, when matching `(a*)+` against `aaa`, PCRE runs the `+` twice, once to match `aaa` and a second time to match the empty string. RE2 runs the `+` only once, to match `aaa`. Because parens capture the rightmost text they matched, for PCRE `$1` will be an empty string while for RE2 `$1` will be `aaa`. The PCRE behavior could be kludged into RE2 if needed.

**Comment by camilstaps** [comment]
@junyer thanks for the explanation! I'm sorry I wasn't more clear - I actually understand on the VM level how RE2 arrives at this result, but I was looking more for a formal definition of what parts of the string is returned as a submatch. If my understanding is correct, RE2 and PCRE will always match the same `$0` (special cases like `\v` aside), and this is what you want since the definition of `$0` is rooted more formally in theory. But if I understand you correctly ("It's just that execution works that way"), we don't have formal semantics for submatch boundaries?

This is just if you have the time and enjoy the question, feel free to skip: I had been working on the articles on the site you linked and testing with the PCRE test suite (not realising there were these differences), but I could not come up with a way to get PCRE's handling of `(a*?)*` into the Pike-style approach. Do you have an idea how you might go about that?

**Comment by junyer** [comment]
For submatches, RE2 follows Perl semantics. (https://swtch.com/~rsc/regexp/regexp2.html#posix describes why not POSIX semantics.) Alas, I don't think that I have seen Perl semantics defined in any formal sense, so where RE2 is "wrong", one could argue that Perl is "right" only because what Perl does is... what Perl does.

Oh, and I honestly don't know how I could make NFA execution produce the same result as Perl in this particular situation. Even BitState execution goes 3, ~5~, 6, 5, ~3~, 4 and suggests no obvious way to "run the `*` twice". But it's possible that I might not be sufficiently imaginative...

**Comment by camilstaps** [comment]
@junyer thank you for taking the time to explain and think with me, this was very helpful! :)

**Comment by junyer** [comment]
You're welcome!

If you want to look into using derivatives for submatches, read some of Martin Sulzmann's papers:

- [September 2012] [Regular expression sub-matching using partial derivatives](https://www.home.hs-karlsruhe.de/~suma0002/publications/ppdp12-part-deriv-sub-match.pdf) PPDP'12
- [April 2014] [A Flexible and Efficient ML Lexer Tool based on Extended Regular Expression Submatching](https://www.home.hs-karlsruhe.de/~suma0002/publications/cc14-flexible-lexing-via-extended-regex.pdf) CC'14
- [June 2014] [POSIX Regular Expression Parsing with Derivatives](https://www.home.hs-karlsruhe.de/~suma0002/publications/regex-parsing-derivatives.pdf) FLOPS'14

I'm wondering whether his "greedy leftmost" semantics agree with RE2 or Perl for `(a*?)*`, `(a*)+` et cetera...

**Comment by junyer** [comment]
FWIW, based only on tinkering with some old code of mine, his semantics seem to agree with RE2.

**Comment by camilstaps** [comment]
@junyer That made for some interesting reading, thank you very much!
