### ISSUE TITLE
FindAndConsumeN does not honor start anchor when used in a loop

### ISSUE THREAD

**Issue by HAT-DK** [google/re2#246]
Consider this regex: "^(?P<first_digit>[0-9]{1})"
Given the text: "1234"

RE2::FindAndConsumeN will actually match 4 times and not the expected 1 time.

Example code snippet
...
while(RE2::FindAndConsumeN(&buffer, pattern, args, count))
{
...
}

Shouldn't StringPiece class hold state on the start anchor?

**Comment by junyer** [comment]
> Shouldn't StringPiece class hold state on the start anchor?

No, it's just a pointer–length pair.

The only difference between `RE2::FindAndConsumeN()` and `RE2::ConsumeN()` is that the former is unanchored whereas the latter is anchored; with an anchored regular expression, they are exactly equivalent. If anything in the documentation misled you, please let me know so that I can correct it, but the behaviour here is intended.

**Comment by spektom** [comment]
@junyer I've stumbled upon the same question.

Can you please advise on a way (a code snippet would be great) on how to extract all pattern matches from a text, whenever a pattern is anchored:

1. Extracting all matches of `^(..)` from `"Hello\nWorld"` produces: `["He"]`
2. Extracting all matches of `(?m)^(..)` from `"Hello\nWorld"` produces: `["He", "Wo"]`

Thanks!

**Comment by junyer** [comment]
For that, you will need to call [`RE2::Match()`](https://github.com/google/re2/blob/b733fc4bff1796842c89ca67a6c4b11e521cde73/re2/re2.h#L551-L577) within a loop and advance `startpos` yourself; [`RE2::GlobalReplace()`](https://github.com/google/re2/blob/b733fc4bff1796842c89ca67a6c4b11e521cde73/re2/re2.cc#L459-L460) does so and handles the edge case where `$0` is the empty string, so it's worth starting there. Just to be clear, unlike the "consume" functions, this approach **_doesn't_** consume the input string, so `^` can't possibly match after `startpos` advances past 0, for example, and `(?m)^` is able to probe before `startpos` in order to check for `\n`.
