### ISSUE TITLE
regex to capture from next line after text

### ISSUE THREAD

**Issue by oviliz** [google/re2#250]
I'm using this regex, `>Version\\s*([\\.\\d]*)<` to capture the version number from https://apps.apple.com/gb/app/my-english-literature-gcse/id1335737542

But having a hard time to figure out how to capture the text that is on the next line like here, https://play.google.com/store/apps/details?id=com.m360.android&hl=en_GB.
![image](https://user-images.githubusercontent.com/73616/77165320-f293a100-6aa9-11ea-98f8-de57dc1ed8ce.png)

Any help please?

**Comment by junyer** [comment]
Your question isn't appropriate for a project's issue tracker and isn't even appropriate for a site like stackoverflow.com. I suggest using a site like regex101.com to debug/test your regular expression. Otherwise, consider using a site like freelancer.com to find/pay someone to help you do this work.
