### ISSUE TITLE
Tweaks to cmake-based build needed for packaging

### ISSUE THREAD

**Issue by foutrelis** [google/re2#274]
I've been asked to [use CMake to build re2](https://bugs.archlinux.org/task/67739) on Arch Linux so it can be consumed by other CMake-based projects like gRPC. There are a couple of issues with this:

1. We still want to ship `re2.pc` as part of a cmake-based build (reverting https://github.com/google/re2/commit/5bd613749fd530b576b890283bfb6bc6ea6246cb would solve this I think)
2. The cmake-based build installs the `re2.so` library without a soname version. Something like the following seems to work:
```
set_target_properties(re2 PROPERTIES VERSION 8.0.0 SOVERSION 8)
```

Of course there would need to be some way to keep the soname consistent between `Makefile` and `CMakeLists.txt`. A single file containing just the major soname version would be easy to read from both build systems. I'm not sure if there's another solution that would be better here.

**Comment by junyer** [comment]
For the record, RE2 supports CMake mostly for the sake of users who don't have GNU make (e.g. Visual Studio users, Xcode users) and only partly – and unenthusiastically – for the sake of CMake users. Having said that, I actually want to help here. :)

Do you happen to know whether there exists any prior art for wrapping CMake's `FindPkgConfig` module in order to provide a CMake package configuration file? Producing an `re2-config.cmake` file in such a way seems as though it should be feasible. (Ping, @mtorromeo and @eli-schwartz for CMake expertise.)

**Comment by eli-schwartz** [comment]
If it isn't found via cmake-config stuff, you could use:

```
find_package(PkgConfig)
pkg_check_modules(RE2 re2 IMPORTED_TARGET GLOBAL)
add_library(OTHERNAME::OTHERNAME ALIAS PkgConfig::RE2)
```

Note for the niceness of `IMPORTED_TARGET GLOBAL` you need cmake >= 3.13

The alias should then let you use a single link name in target_link_libraries to link to re2, whether it's found by the generic buildsystem-agnostic pkg-config or the only-works-in-cmake cmake-config files.

IMO this is the responsibility of downstream consumers to check for the pkg-config value since that's the "official" build system for re2. But I bet you could install a simple FindRe2.cmake statically coding this content to make autotools installs still be detected by people using only find_package().

**Comment by eli-schwartz** [comment]
Incidentally, cmake is a terrible build system, and my understanding is re2 considers support for simultaneous shared/static libraries to be a hard requirement for building. Which of course cmake doesn't support.

It's not just autotools which does support it, Meson has a core option `-Ddefault_library=[shared|static|both]`.
Meson has both an XCode backend and a VS backend. No Make backend though, since it chose Ninja instead.

meson even has a cmake module for generating cmake config files, for the unfortunate cmake users: https://mesonbuild.com/CMake-module.html#cmake-configuration-files
Though pkg-config is preferred as it works on any platform and any build system.

**Comment by mtorromeo** [comment]
@junyer No, sorry. I'm not even a CMake user, let alone an expert. I only learned about it enough to be able to package things that use it and make minor patches when I needed to.

**Comment by junyer** [comment]
Thanks for following up so promptly!

> IMO this is the responsibility of downstream consumers to check for the pkg-config value since that's the "official" build system for re2. But I bet you could install a simple FindRe2.cmake statically coding this content to make autotools installs still be detected by people using only find_package().

Ahh. Good point. I see that gRPC provides https://github.com/grpc/grpc/blob/master/cmake/modules/Findc-ares.cmake, so it might be reasonable for them to provide `Findre2.cmake` as well. And going by your example, it would be very straightforward. What do you reckon, @donnadionne and @jtattermusch?

**Comment by junyer** [comment]
https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html?highlight=stream seems to say that `re2-config.cmake` would be something for RE2 to provide whereas `Findre2.cmake` would be something for gRPC to provide. Also, I notice that gRPC currently requires the former because they specify `CONFIG` to `find_package()`:

https://github.com/grpc/grpc/blob/10006758d0b3f53a3a996413b550120bfe4a4feb/cmake/re2.cmake#L47-L48

**Comment by eli-schwartz** [comment]
I only know enough about cmake to fight it into building external projects I need to build. :p The nuances of Find*.cmake vs. *-config.cmake escape me. I know the latter usually seem to come in multiple parts but otherwise seem to fullfill the exact same roles.

Does that mean you could just install one file named re2-config.cmake with the statically coded pkg_check_modules() contents?

**Comment by foutrelis** [comment]
/usr/lib/cmake/re2/re2Config.cmake with the following content seems to allow grpc 1.31.x to link against system libre2.so:

```
set(RE2_INCLUDE_DIRS /usr/include)
set(RE2_LIBRARY_DIR /usr/lib)
set(RE2_LIBRARIES -L${RE2_LIBRARY_DIR} -lre2)
```

The paths can be set by the Makefile like it's done for re2.pc. It's worth noting that I get relocation errors by the linker when throwing libre2.a at it (i.e.: doing a static-install build of re2). Linking to the shared library is fine though. :)

I also get a failure later on because the python bindings are hardcoded to use the bundled re2. That's out of scope for this bug though.

**Comment by foutrelis** [comment]
> I get relocation errors by the linker when throwing libre2.a at it

Wow, the linker was actually telling me the correct thing about needing -fPIC. I was seeing lots of `-fPIC` when building re2 but those were coming from the object files used for the shared library. The objects that get into libre2.a are not compiled with -fPIC, thus the relocation errors when linking them into libgrpc.so.

So, turns out the re2Config.cmake above also works with libre2.a. Might be worth building it with -fPIC though. :)

**Comment by foutrelis** [comment]
I no longer consider the above cmake config file to be the correct approach. The `RE2_INCLUDE_DIRS` and `RE2_LIBRARIES` variables feel too specific to gRPC. Perhaps it's better not to add anything to re2 and rely on downstream projects to use the pkg-config module for CMake.

**Comment by eli-schwartz** [comment]
`*_INCLUDE_DIRS` and `*_LIBRARIES` is just a *bad* interface and does not handle correctly translating arguments the way an interface library does.

You can get `*_INCLUDE_DIRS` and `*_LIBRARIES` from pkg_get_modules too. It's just a bad idea, since pkg-config is supposed to return a metaphor for an "object" capable of being linked to your project.
- in meson, the return type of a pkg-config `dependency()` is always a meson DependencyHolder object which you can then link to
- in autotools it just returns the final linker strings, which you use as-is and it works
- in cmake, there'a no such thing as returning, but instead it defines (as a side effect) global variables for `*_INCLUDE_DIRS` and `*_LIBRARIES` which cannot even be used as-is, because they're lists. Lists which are defined as ";"-separated strings.

`IMPORTED_TARGET GLOBAL` is the solution to this bad design decision of old-style cmake. Having previously broken upstream projects by trying to use `*_INCLUDE_DIRS` and `*_LIBRARIES` and having it unpredictably mangle the arguments passed to the compiler, I've learned my lesson and now know to stick with proper targets.

**Comment by junyer** [comment]
> Does that mean you could just install one file named re2-config.cmake with the statically coded pkg_check_modules() contents?

If it turns out that RE2 should provide a CMake package configuration file, I would plumb the results from `FindPkgConfig`. With the `;`-separated lists expanded, I imagine, if that's what's needed for a drop-in replacement of an "authentic" CMake package configuration file.

> So, turns out the re2Config.cmake above also works with libre2.a. Might be worth building it with -fPIC though. :)

`FindPkgConfig` should define `re2_FOUND` et al. for `libre2.so` and `re2_STATIC_FOUND` et al. for `libre2.a`, apparently, and then the CMake package configuration file would expose one or the other depending on the value of `BUILD_SHARED_LIBS`?

> `IMPORTED_TARGET GLOBAL` is the solution to this bad design decision of old-style cmake. Having previously broken upstream projects by trying to use `*_INCLUDE_DIRS` and `*_LIBRARIES` and having it unpredictably mangle the arguments passed to the compiler, I've learned my lesson and now know to stick with proper targets.

In theory, just having the `re2::re2` target should be sufficient. In practice, it seems like that's not the case for all users. :(

**Comment by junyer** [comment]
gRPC folks, it would be great to hear your thoughts on all of this – especially if you know CMake better than the rest of us do!

**Comment by junyer** [comment]
Ping, @donnadionne and @jtattermusch! :)

**Comment by veblush** [comment]
@junyer I hope that I can answer your questions but Jan is the right person for cmake since he is a primary author of cmake files of gRPC and Donna might know re2-specific issues.

**Comment by eli-schwartz** [comment]
> In theory, just having the `re2::re2` target should be sufficient. In practice, it seems like that's not the case for all users. :(

Can you clarify what you mean by this?

**Comment by donnadionne** [comment]
@jtattermusch would definitely be the best person to comment on cmake.

I just know from my limited experience working with cmake that:
1. We generally don't want to make our build more complex by adding more build options into cmake/re2.cmake
2. find_package will not work for re2, so writing a finder is needed: https://github.com/google/re2/issues/215
3. We accepted the contribution of Findc-ares.cmake: https://github.com/grpc/grpc/pull/20815 (approved by Jan), so I think we would be able to accept something similar for re2.

**Comment by junyer** [comment]
> Can you clarify what you mean by this?

https://github.com/grpc/grpc/blob/10006758d0b3f53a3a996413b550120bfe4a4feb/cmake/re2.cmake#L52-L53 covers the case where the `re2::re2` target doesn't exist. Likewise in a couple of other `.cmake` files nearby. I don't quite understand its purpose yet.

> 3. We accepted the contribution of Findc-ares.cmake: https://github.com/grpc/grpc/pull/20815 (approved by Jan), so I think we would be able to accept something similar for re2.

Thanks, @donnadionne! If that sounds reasonable to you, @veblush, I will attempt to contribute `Findre2.cmake` in the near future. (I'm guessing that Arch Linux folks would like to package the new release sooner rather than later, so we presumably can't just wait for @jtattermusch to get back.)

**Comment by eli-schwartz** [comment]
As far as I can tell, that re2 finder tries to find re2 via a re2-config.cmake, then manually checks if the *config package* fails to export a re2::re2 target. This is of course impossible if re2-config.cmake came from this repository, and also improbable, I should think, if it came from anywhere else that was a *config* file rather than a Find*.cmake file as the whole point of a config file is it provides an exported target.

The only thing I can think of is that maybe the grpc re2.cmake is trying to cover the case where the target is installed with a different namespace other than `NAMESPACE re2::`, and as the target name might not be predictable, perform one last desperate attempt to get the raw libraries.

If, however, the `re2::re2` target *is* available and linkable, I don't see a problem with using it.

**Comment by junyer** [comment]
Thanks, @eli-schwartz, that makes sense to me. And now making things resemble https://github.com/grpc/grpc/blob/cd56d6664395f93dcc3ff1564df2d0d034275190/cmake/cares.cmake#L41-L45 also makes sense to me. :)

**Comment by veblush** [comment]
@junyer Yeah, it sounds reasonable to me!

**Comment by junyer** [comment]
Thanks, @veblush! I have the C++ tests building and passing with `Findre2.cmake` looking like this:

```
find_package(PkgConfig)
pkg_check_modules(RE2 re2)
if(RE2_FOUND)
  add_library(re2::re2 INTERFACE IMPORTED)
  set_target_properties(re2::re2 PROPERTIES
    INTERFACE_COMPILE_OPTIONS "${RE2_CFLAGS}"
    INTERFACE_LINK_LIBRARIES "${RE2_LDFLAGS}"
    )
endif()
```

However, a few things need some polish before I can send you a pull request. And I need some sleep. :)

**Comment by junyer** [comment]
Sent https://github.com/grpc/grpc/pull/24088.

**Comment by junyer** [comment]
https://github.com/grpc/grpc/pull/24088 was merged as https://github.com/grpc/grpc/commit/52299822737ef4d4418296695dc061575f10f5f3.

Arch Linux folks, I'm guessing that you will need to wait for the next release of gRPC... unless you carry the patch temporarily?

**Comment by junyer** [comment]
I'm closing this issue optimistically. Many thanks, everyone, for your support and solidarity in the face of unrelenting CMake. :)

**Comment by mtorromeo** [comment]
Thanks to everyone involved!

> Arch Linux folks, I'm guessing that you will need to wait for the next release of gRPC... unless you carry the patch temporarily?

No problem, I'll add the patch manually if it's not merged before I get to packaging it

**Comment by drin** [comment]
(thank you, I greatly appreciate this thread and all of its contributors)
