### ISSUE TITLE
Vim-style branch (\&) operator

### ISSUE THREAD

**Issue by mattfs** [google/re2#279]
In lieu of a positive lookahead match, having access to a Vim-style branch (`\&`) [1] operator would be very helpful. This operator is not currently documented in the re2 wiki as either supported or unsupported, but would be useful for wallpapering over the lack of positive lookahead.

The branch operator is the AND analogue to the alternation operator's OR.

I was not able to find another example of this operator in any other regular expression language. It appears to be unique to Vim.

[1] https://stackoverflow.com/questions/18309859/what-is-the-pattern-in-vims-regex

**Comment by junyer** [comment]
Without even considering the implementation problem, the interface problem rules this out for RE2 because `\&` would suddenly change meaning. People very often escape characters that don't need escaping, so the risk of breakage isn't negligible. (Note that PCRE features hide behind `(?`, which can never appear in a valid regular expression otherwise.)
