### ISSUE TITLE
2020-11-01: re2.pc file is not installed

### ISSUE THREAD

**Issue by kloczek** [google/re2#294]
L:ooks like install target is not installing re2.pc pkgconfig file.

**Comment by junyer** [comment]
Were you building with GNU make? Or with CMake?

If with GNU make, I would need detailed information in order to determine what went wrong. I see that Arch, Debian, Ubuntu et cetera have packages for release `2020-11-01`, so installing the `.pc` file is evidently not broken for everyone.

If with CMake, please note that we expect packaging to use GNU make and so we don't configure CMake to install the `.pc` file.

**Comment by kloczek** [comment]
So please accept very simple fact that most of the Linux distributions already are using cmake to build re2.
