### ISSUE TITLE
Is the python binding a faithful map into re2 functionality?

### ISSUE THREAD

**Issue by MartinHowarthMeta** [google/re2#307]
I'm looking at using the python package that you now publish in our python project - previously I built using https://github.com/facebook/pyre2 from source, but would much rather just have a pip-installable version.

However, the sentence in the setup.py "A drop-in replacement for the re module." (https://github.com/google/re2/blob/abseil/python/setup.py#L8) is concerning. To match the facebook wrapper, I'm looking for python bindings to re2 that don't change the behaviour, rather than trying to be a drop-in replacement for the python `re` library. 

One of the reasons for this perference is that `re` has changed behaviour between python minor versions (e.g. https://bugs.python.org/issue1647489 - `re.sub("(.*)", "\\1;replacement", "original")` differs betwen 3.6 and 3.7+), so trying to be a "drop in replacement for re" then matters which version of python you're using. All software has bugs, but it seems onerous to then aim to replicate these changes in your bindings (if you're aiming for a fully accurate drop-in replacement).

I can see that both versions of the python bindings would be good to have. Maybe you could published two packages? Or have a flag that preserves re2 behaviour as much as possible? Currently there are no python packages which aim to just behave like re2, but there is already one (any maybe more) that aim to be a drop-in replacement for `re`, e.g. https://github.com/andreasvc/pyre2

Can you comment on what the current behaviour is, and what the intended direction for the future of the python bindings is?

**Comment by junyer** [comment]
The `re2` module doesn't – and won't – try to behave like the `re` module down to the level of the underlying engine. The goal is just to behave similarly at the level of the Pythonic interface.  It's duck typing, I suppose, insofar as the classes and methods are (mostly) compatible in terms of names and types, but there are subtle things about this duck like the fact that it has a tin leg. :P

With regard to the bug that you mentioned, the `re2` module has always behaved how the `re` module in Python 3.7+ behaves:

```
Python 3.6.13 (default, Apr  5 2021, 12:44:51)
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.sub("(.*)", "\\1;replacement", "original")
'original;replacement'
>>>
```

```
Python 3.7.10 (default, Apr  5 2021, 12:45:14)
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.sub("(.*)", "\\1;replacement", "original")
'original;replacement;replacement'
>>>
```

```
Python 3.9.4 (default, Apr  5 2021, 12:46:08)
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re2
>>> re2.sub("(.*)", "\\1;replacement", "original")
'original;replacement;replacement'
>>> 
```

FWIW, Perl agrees:

```
$ echo original | perl -lpe "s/(.*)/\\1;replacement/g;"
original;replacement;replacement
$ 
```

OTOH, `GlobalReplace()` in C++ has always behaved how the `re` module in Python 3.6 behaves. This predates my tenure and I happen to disagree with it, but there's no way that it's going to change at this point. Moreover, the `re2` module doesn't use it to implement `sub()` because its substitutions aren't powerful enough; I was free to build atop `finditer()` and let **_that_** DTRT.

**Comment by MartinHowarthMeta** [comment]
Thanks for the quick response :)

That's the answer I was hoping for, and I also found https://stackoverflow.com/questions/52351217/why-do-some-regex-engines-match-twice-in-a-single-input-string to further explain the problem I was seeing. Basically matching on `(.*)` differs between various regex engines and matching on `(^.*)` is more consistent.
