### ISSUE TITLE
"invalid perl operator" error message is confusing

### ISSUE THREAD

**Issue by mirt001** [google/re2#315]
Currently, the error message for an invalid re2 operator is ```invalid perl operator``` in [regexp.cc](https://github.com/google/re2/blob/5aec8b553863350e32d13bbf745eae81adcdce93/re2/regexp.cc#L506).

This is confusing, as it suggests the user to check the perl compatibility for the operator. Some operators are valid perl operators, but invalid re2 operators. E.g., look around operators are supported by perl, but not by RE2.

The error message should say ```invalid re2 operator```.

Similarly, but less impactful, the enumerator identifier ```kRegexpBadPerlOp``` should be changed to ```kRegexpBadRe2Op``` in [regexp.h](https://github.com/google/re2/blob/5aec8b553863350e32d13bbf745eae81adcdce93/re2/regexp.h#L186).

Of course, changing ```kRegexpBadPerlOp``` to ```kRegexpBadRe2Op``` should be reflected [everywhere it's used](https://github.com/google/re2/search?q=kRegexpBadPerlOp&type=code).

A [simple google search](https://www.google.com/search?q=%22invalid+perl+operator%22) shows that modifying this error message would have a great impact, since re2 is used in so many google products, e.g. google spreadsheets, google earth engine, etc. This change would greatly reduce confusion among end of chain developers.

A direct example of such confusion can be found in [this stackexchange question](https://gis.stackexchange.com/questions/403274/how-to-do-a-regex-negative-lookahead-in-a-ee-string-replace).

This issue is probably a low-hanging fruit, since the solution feels easy to implement, but the beneficial impact would be major.

**Comment by junyer** [comment]
I certainly agree that `"invalid perl operator"` isn't clear and, similarly, that `kRegexpBadPerlOp` and `RE2::ErrorBadPerlOp` aren't clear. Changing an enum is relatively straightforward because you can (temporarily) support two names with the same value or you can change the name and people will typically notice when builds start breaking. Changing a string is somewhat fraught, OTOH, because people can – and do – write code that checks string values and there's no way to avoid breakage or even just to surface it reliably and noisily. (The best that we can hope for there is that such people have good test coverage.) This is a boring case of [Hyrum's law](https://www.hyrumslaw.com/), I'm afraid, so although I'm inclined to improve the error, I'm **_more_** inclined to let it be for the sake of not causing problems. Sorry. :(
