### ISSUE TITLE
NO_THREADS missing

### ISSUE THREAD

**Issue by terpstra** [google/re2#324]
In some situations (including embedded systems), even if threads are available we don't want to link the associated library. NO_THREADS used to support this. However, it seems to be removed since 2016. I'd just continue to use an older version, but I need some of the bug fixes since then.

Could this feature please be restored?

**Comment by junyer** [comment]
`NO_THREADS` was used in [`util/mutex.h`](https://github.com/google/re2/blob/3d5f1714e63f50ce5ef92daa580cb2cdb18f2a0e/util/mutex.h#L86-L103) to make `Mutex` a no-op. It could be resurrected, I suppose, but there's more than just `Mutex` nowadays. Does your toolchain make `std::once_flag`/`std::call_once()` a no-op? Or would they have to be replaced throughout the RE2 codebase? If the latter, I can help you get it to work, but I would rather not support this use case upstream.

**Comment by terpstra** [comment]
When I inspected the generated assembly, std::call_once did not appear to be a no-op. Nevertheless,

```
--- util/mutex.h.orig	2021-08-29 10:01:58.819148565 -0700
+++ util/mutex.h	2021-08-29 10:02:29.611102870 -0700
@@ -26,7 +26,9 @@
 #endif
 #endif
 
-#if defined(MUTEX_IS_WIN32_SRWLOCK)
+#if defined(NO_THREADS)
+typedef char MutexType;
+#elif defined(MUTEX_IS_WIN32_SRWLOCK)
 typedef SRWLOCK MutexType;
 #elif defined(MUTEX_IS_PTHREAD_RWLOCK)
 #include <pthread.h>
@@ -64,7 +66,16 @@
   Mutex& operator=(const Mutex&) = delete;
 };
 
-#if defined(MUTEX_IS_WIN32_SRWLOCK)
+#if defined(NO_THREADS)
+
+Mutex::Mutex()             { }
+Mutex::~Mutex()            { }
+void Mutex::Lock()         { }
+void Mutex::Unlock()       { }
+void Mutex::ReaderLock()   { }
+void Mutex::ReaderUnlock() { }
+
+#elif defined(MUTEX_IS_WIN32_SRWLOCK)
 
 Mutex::Mutex()             { InitializeSRWLock(&mutex_); }
 Mutex::~Mutex()            { }
```

... fixed my problem.

**Comment by junyer** [comment]
Sorry, I misspoke earlier: `std::once_flag`/`std::call_once()` can't be a no-op because they have to do ***something*** in order to provide their functionality; what I intended to say was that, in your toolchain, they don't require threading support. At this point, the yak becomes a bit hairier... Although making `Mutex` a no-op solves your problem, I think that honouring `NO_THREADS` would have to mean promising to avoid using any such mechanisms regardless of their availability and/or functionality under the hood; otherwise, we could force the use of `std::mutex` and require the toolchain to make it a no-op, but do ***all*** toolchains actually do that? For now, given that you have a patch that works for you and that nobody else has flagged this as an issue for them, please carry the patch locally. I'm more than happy to revisit this if there's more need and we can identify a clear, clean way forward.
