### ISSUE TITLE
Optional integer argument causes rest of matches to not get filled

### ISSUE THREAD

**Issue by hugoam** [google/re2#326]
Hello,

It seems RE2 displays some weird and unexpected behavior specifically with optional capture group mapping to an integer argument
When mapping to a string argument and an optional group is not present, the following groups get matched correctly. However, when mapping to an integer argument, the following groups don't get matched if the optional integer match was not present.

In the following example, `ext` match is after an optional capture group mapping to a string, and it gets matched even though the previous group was not matched, which is expected
```
std::string popo;
std::string test;
std::string ext;
RE2 regex("(popo)?(test)?(ext)?");
RE2::FullMatch("popoext", regex, &popo, &test, &ext); // both popo and ext are matched (GOOD)
```

In the following example however, `ext` match is after an optional capture group mapping to a int, and it does **not** get matched, which is very surprising and actually kind of problematic
```
std::string popo;
int number;
std::string ext;
RE2 regex("(popo)?(\\d{3})?(ext)?");
RE2::FullMatch("popoext", regex, &popo, &number, &ext); // only popo is matched, but ext is not matched (BAD)
```

A workaround seems to be to pass a string argument instead, and do the integer conversion myself, but it would be better if RE2 behaved consistently in that regard, I believe
```
std::string popo;
std::string number;
std::string ext;
RE2 regex("(popo)?(\\d{3})?(ext)?");
RE2::FullMatch("popoext", regex, &popo, &number, &ext); // both popo and ext are matched (GOOD)
```

**Comment by junyer** [comment]
When calling `RE2::FullMatch()` et al., it's important to check the return value so that you don't then try to read the arguments when they are in an indeterminate state. (Refer to https://github.com/google/re2/blob/main/re2/re2.h#L71-L81 for more details.)

The other problem here is that, yes, if the capturing group has captured nothing, then integer conversion will fail. To handle that case explicitly, write a class `Optional` with a member function of the form `bool Optional::ParseFrom(const char*, size_t)`: if the capturing group has captured nothing, return `true`; otherwise, perform integer conversion as normal. You can then pass an `Optional*` to `RE2::FullMatch()` et al. instead of an `int*`.

Someday, RE2 will be able to require C++17... and then we will support `std::optional<>` out of the box. :)

**Comment by hugoam** [comment]
> When calling RE2::FullMatch() et al., it's important to check the return value so that you don't then try to read the arguments when they are in an indeterminate state

Well actually the API is a little bit clumsy in that aspect, as out of the box the boolean is useless when attempting to parse a bunch of optional capture groups (it will return false when not all have been matched). I voluntarily don't check the return, because it doesn't play well with optional capture groups.

If I understand what you're saying and briefly skimming your linked comment, it seems you're saying I could write a lot of custom code to support optional capture groups by myself instead of just passing raw arguments or `Arg`, and then maybe I would get good behavior (the function returning true even if not all groups were captured), but frankly I don't know if I have the motivation to figure this out by myself. In my opinion, the library could provide an easy way to do so even without supporting C++17 ?

**Comment by hugoam** [comment]
Also, a point that I did not see your answer address is that strictly speaking in both cases above, nothing was captured by the Nth group, whether you want to parse `no capture` as an int or as a string, so the fact that `Arg(int*)` behaves differently than `Arg(std::string*)` when processing group that captured nothing still seems like a problematic inconsistency.

**Comment by junyer** [comment]
If the capturing group has captured nothing, then the argument parser is passed a null pointer and a zero length. Converting to `std::string` should produce the empty string for hopefully obvious reasons whereas converting to `int` should fail for, again, hopefully obvious reasons. The users who want different semantics implement custom argument parsers or use `RE2::Match()` instead of `RE2::FullMatch()` et al.
