### ISSUE TITLE
Get positions of matches with RE2::set

### ISSUE THREAD

**Issue by estebanpw** [google/re2#353]
Hello,

I am working with RE2 and I was wondering if there is a function for either extracting either the matched values or the positions for the `re2::set` implementation (so matching multiple regexes at once), e.g. something similar to `RE2::FindAndConsume(&input, "(\\w+)", &word)` but for sets.

As far as I can tell, the only matching function for `re2::set` is `bool Match(const StringPiece& text, std::vector<int>* v, ErrorInfo* error_info) const;` which provides the integer ids of the matched patterns, but not the positions or the matches values.

Am I missing something?

Thank you for your time!

**Comment by junyer** [comment]
Indeed, `RE2::Set` outputs **_which_** regular expressions matched, but not **_where_** they matched. Under the hood, it uses the DFA execution engine, so it could be possible to output the end of each match, but not the start of the match... without running the corresponding regular expression backwards. There's also the matter of any given regular expression matching multiple times (potentially overlapping), which would require a new interface and implementation in order to track and output all matches for all regular expressions in an efficient way. All of which is to say that you probably want to look into using [Hyperscan](https://github.com/intel/hyperscan) instead. :)

**Comment by estebanpw** [comment]
Hello @junyer,

thank you for answering so quickly! In fact I was already working with hyperscan too - and I wanted to compare it with RE2.

Thanks for your time!
