### ISSUE TITLE
Errors when compiling projects in visual studio.

### ISSUE THREAD

**Issue by InsaneMiner** [google/re2#364]
Here is my fix: https://github.com/InsaneMiner/re2/commit/fceb5222776fe9caa947ca0fe350be6485d27e71

**Comment by junyer** [comment]
Thanks for the patch. From reading https://stackoverflow.com/a/5004874, I suspect that you would be better off defining the `NOMINMAX` macro at the Visual Studio project level. At least, I gather that's what everyone else does – because this is the first reported issue regarding such breakage ever since we originally got RE2 building with Visual Studio several years ago. :)

**Comment by InsaneMiner** [comment]
@junyer i did try that, but it still didn't work for me.

**Comment by junyer** [comment]
Without knowing the details, I'm not sure what to suggest.

**Comment by InsaneMiner** [comment]
> Without knowing the details, I'm not sure what to suggest.

i just patched it on my system, so im alright.

**Comment by junyer** [comment]
Fair enough. :)
