### ISSUE TITLE
Link to syntax checker

### ISSUE THREAD

**Issue by hickford** [google/re2#373]
It would be super helpful if the wiki page https://github.com/google/re2/wiki/Syntax linked to a website you can use to check re2 syntax.

I know of:

1. https://goto.google.com/regex-checker (Googlers only)
2. https://regoio.herokuapp.com/ (Go implementation, checks syntax when you press enter)

**Comment by junyer** [comment]
I generally avoid linking to any other projects because I don't want to curate a directory. (Wrappers are the notable exception because otherwise "can I use RE2 in language XYZ?" would be an FAQ.) Searching for `regular expression syntax checker` on Google and Bing returns regex101.com as the first result, evidently, so discoverability doesn't appear to be a problem. I'm also exceedingly reluctant to reinforce the erroneous belief that RE2 and the Go `regexp` package are one and the same, so I wouldn't link to regoio.herokuapp.com anyway.
