### ISSUE TITLE
google-re2 python library is broken in macos

### ISSUE THREAD

**Issue by davidorlov12** [google/re2#375]
`Collecting google-re2
  Using cached google-re2-0.2.20220401.tar.gz (8.9 kB)
Using legacy 'setup.py install' for google-re2, since package 'wheel' is not installed.
Installing collected packages: google-re2
  Attempting uninstall: google-re2
    Found existing installation: google-re2 0.2.20220401
    Uninstalling google-re2-0.2.20220401:
      Successfully uninstalled google-re2-0.2.20220401
    Running setup.py install for google-re2 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gw/r4wz7n_s5xv7573tnjjbz43w0000gn/T/pip-install-ef9hfwko/google-re2_d9c8e8123a6642909bb2495dfef98321/setup.py'"'"'; __file__='"'"'/private/var/folders/gw/r4wz7n_s5xv7573tnjjbz43w0000gn/T/pip-install-ef9hfwko/google-re2_d9c8e8123a6642909bb2495dfef98321/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gw/r4wz7n_s5xv7573tnjjbz43w0000gn/T/pip-record-nk0t09sm/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/google-re2
         cwd: /private/var/folders/gw/r4wz7n_s5xv7573tnjjbz43w0000gn/T/pip-install-ef9hfwko/google-re2_d9c8e8123a6642909bb2495dfef98321/
    Complete output (176 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-universal2-3.10
    copying re2.py -> build/lib.macosx-10.9-universal2-3.10
    running build_ext
    building '_re2' extension
    creating build/temp.macosx-10.9-universal2-3.10
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pybind11/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c _re2.cc -o build/temp.macosx-10.9-universal2-3.10/_re2.o -fvisibility=hidden
    In file included from _re2.cc:11:
    In file included from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pybind11/include/pybind11/pybind11.h:13:
    In file included from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pybind11/include/pybind11/detail/class.h:12:
    In file included from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pybind11/include/pybind11/detail/../attr.h:13:
    In file included from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pybind11/include/pybind11/cast.h:13:
    /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pybind11/include/pybind11/detail/common.h:460:17: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
    using ssize_t = Py_ssize_t;
                    ^
.
.
.
.
.
.
`

to fix this run:
brew install re2
brew install pybind11
export CFLAGS="-std=c++11 -I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib/"
pip3 install google-re2

**Comment by junyer** [comment]
I won't be cutting a new release for another two weeks yet, so let's give Homebrew folks a little while to respond. ;)

Also, I release wheels for Python 3.7 through 3.10 on `manylinux2014_aarch64` and `manylinux_2_24_aarch64`. Were those not useful for some reason? (The users who reported this build failure previously never responded regarding the wheels.)

**Comment by alebcay** [comment]
Hi @junyer and @davidorlov12, not the biggest Python expert from Homebrew (this issue has been circulated in our internal Slack) but there's a one thing we did notice from the logs above:

> `Using legacy 'setup.py install' for google-re2, since package 'wheel' is not installed. Installing collected packages: google-re2`

Not sure what your Python environment looks like, but this seems a bit odd. If you have the `wheel` package installed, you should hopefully be able to use prebuilt wheels (if they're available for your platform/architecture). All of the Pythons provided by Homebrew should ship with the `wheel` package.

As for the magic `export CFLAGS="-std=c++11 -I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib/"`, you _may_ be able to get by without the `-std=c++11` flag. However, the `-I` portion of `CFLAGS` and `LDFLAGS` are needed here because you are presumably trying to link against the `re2` shipped by Homebrew, which is located in `/opt/homebrew/include` and `/opt/homebrew/lib` and not part of the default compiler search paths (on macOS, you can view the default include search paths with `cpp -v /dev/null -o /dev/null` and the default library search paths with `cc -Xlinker -v`).

Thus you'd only run into the need for this workaround if you're specifically trying to build against Homebrew's components. Maybe it can be documented, but I'm not sure if it should be baked into your `setup.py`.

For instance, someone may try to use `re2` provided from MacPorts and that would live in a different location, or maybe they even have their own built version of `re2` that lives in some arbitrary place. In fact, users can install Homebrew to arbitrary places too (not always `/opt/homebrew`) and then the location of the header/library files would differ.

**Comment by junyer** [comment]
The updated text should be visible on PyPI as of the `2022-06-01` release.

**Comment by junyer** [comment]
FYI, https://pypi.org/project/google-re2/1.0/ has wheels for macOS.
