### ISSUE TITLE
CMake Error when cross compiling for aarch64

### ISSUE THREAD

**Issue by dehmarc** [google/re2#380]
Hello,

I am trying to cross compile version 2022-02-01 for aarch64 using a gcc-based cross compile toolchain..
Im getting the following error:

> -- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   THREADS_PTHREAD_ARG (advanced)
For details see MY_BUILD_FOLDER/TryRunResults.cmake
-- Check if compiler accepts -pthread - no
-- Found Threads: TRUE  

It seems that the issue was introduced here: [Commit ae1e29497bfb0345a59488262f006220e736e53d](https://github.com/google/re2/commit/ae1e29497bfb0345a59488262f006220e736e53d)

The issue is resolved by commenting out [CMakeLists.txt - line 51](https://github.com/google/re2/blob/885eb38accf49e2ccdd2fa6786f3590cf40a3e23/CMakeLists.txt#L51)
`set(THREADS_PREFER_PTHREAD_FLAG ON)`

Maybe the above command should be wrapped around
`if (NOT CMAKE_CROSSCOMPILING)
    ...
endif()`

Is this issue already known or is there a better solution in place?

Seems like this issue also exists for the newer versions...

**Comment by junyer** [comment]
As per https://gitlab.kitware.com/cmake/cmake/-/issues/16920 and https://gitlab.kitware.com/cmake/cmake/-/commit/d4e551a90b6bf6ea4e18fa408f40f39df6ad6fb4, this was a CMake bug that was fixed in version 3.10.0. Given that RE2 currently requires version 3.10.2 at minimum, I don't think there's anything that's needed here. (However, note that the last comment on the issue seems to provide a workaround for older versions.)
