### ISSUE TITLE
Consider performance improvements using x86 SIMD instructions to try to match performance of Hyperscan RE engine 

### ISSUE THREAD

**Issue by jmarantz** [google/re2#383]
See
 * https://github.com/intel/hyperscan
 *  https://github.com/envoyproxy/envoy/issues/19472
 * https://github.com/envoyproxy/envoy/pull/19473

Hyperscan uses SIMD instructions and claims to be around 50% faster (depending on how you measure) compared to re2 on a benchmark.  Note that the engine uses PCRE syntax and is built with x86 SIMD instructions so it's not compatible with re2 or as portable. But I thought I'd bring it up to see if the re2 maintainers might want to try to improve performance using these techniques. I have no idea if this would be feasible for re2.

From the perspective of the Envoy proxy it seems unfortunate to have to carry around a second regex syntax for URL path matching. In some setups, URL path matching is a bottleneck when running http proxies.

**Comment by BurntSushi** [comment]
I don't work on RE2, but I do work on Rust's regex library which is greatly influenced by RE2. One of the biggest differences between RE2 and the regex crate is that the regex crate does more aggressive literal optimizations than RE2. And indeed, it borrows [some algorithms from Hyperscan](https://github.com/BurntSushi/aho-corasick/tree/master/src/packed/teddy). So my background out of the way, I'll share some thoughts:

* Hyperscan probably spends quite a bit more time compiling regexes than RE2 does. RE2 really has to care about compile times because it is a general purpose regex library.
* RE2 does actually already use SIMD (via `memchr`). So "use SIMD" isn't really what you're asking for here. What you're asking for here is to port a whole host of specialized explicit SIMD algorithms (many of which are not documented at all) from one regex engine to another.
* Hyperscan has different match semantics than RE2. Hyperscan reports matches as soon as they are detected. RE2 tries to mimic backtrackers that have greediness and what not. So when you port stuff from Hyperscan, you need to be careful to account for this. (It is, in many cases, non-trivial.)
* Hyperscan, in order to scale to many patterns, has a totally different architecture than RE2. Its high level approach is [described in this paper](https://www.usenix.org/system/files/nsdi19-wang-xiang.pdf). RE2 would have to change a lot of its internals to adapt that I think. It would be a big effort.

It might be the case that it would be reasonable to ask RE2 to do more aggressive literal optimizations, but whether that actually helps or improves your specific use case isn't particularly clear to me.

> From the perspective of the Envoy proxy it seems unfortunate to have to carry around a second regex syntax for URL path matching.

It sounds like performance is an important goal for you. You might then consider building a more bespoke solution to the path matching problem. For example: https://github.com/ibraheemdev/matchit --- That's certainly going to be a lot less work than this request. :-)

**Comment by rsc** [comment]
In addition to @BurntSushi's excellent response, I would just point out that I don't see anything on a quick skim of the Envoy issues and PRs that measures the regexp performance in the context of an actual Envoy workload. I only see microbenchmarks. What does a typical Envoy regexp workload look like? How many different regexps, what are some representative ones, and how many matches happen between changes to the regexp set?

**Comment by jmarantz** [comment]
Thanks! This is a very helpful response.

I'm a bit skeptical that integrating Hyperscan into Envoy is worth it compared to RE2, and agree that:
 * the cases presented are microbenchmarks and may not provide meaningful benefit in the context of other work
 * scenarios where lots of regexes for URL path matching are used are better expressed as a trie or other strategy.
 * For other uses I think re2 is more than good enough. E.g. I switched stats filtering from std::regex to re2 and the benefit was more like 10x or better.

Hyperscan is being proposed as part of a "contrib" package and the Envoy policy has been that we are erring on the side of welcoming contributions if there is potential value and an identified end-user. It would not be compiled-in by default. In this case I'm concerned about bifurcating the Envoy usage model.

I submitted this issue to see whether a better angle might be to "borrow" some of the tactics used in Hyperscan to to try and reduce the perceived performance gap. It looks like the technical tradeoffs and challenges have been well considered. Thanks for the comments!

I'll go ahead and close this.

**Comment by junyer** [comment]
You could conceivably use [`FilteredRE2`](https://github.com/google/re2/blob/main/re2/filtered_re2.h), but it isn't always going to be a net win. In fact, it isn't always obvious whether it's going to be a net win. Just scanning the input string for "atom" strings (using Aho–Corasick, for example, or [`RE2::Set`](https://github.com/google/re2/blob/main/re2/set.h)) can potentially take longer than iterating over a small number of patterns that all have their prefixes matched with `memcmp(3)`.
