### ISSUE TITLE
`#include <shared_mutex>` requires cxx_std_17 while cmake sets cxx_std_11

### ISSUE THREAD

**Issue by evetion** [google/re2#390]
We're cross-compiling re2 over at https://github.com/JuliaPackaging/Yggdrasil/pull/5440 and it works well, except for the mingw builds. Those fail with `fatal error: shared_mutex: No such file or directory`.

The code in `util/mutex.h` specifies `#include <shared_mutex>` in these cases, but this only works [since C++17](https://en.cppreference.com/w/cpp/thread/shared_mutex), while the cmake settings specify C++11.

**Comment by junyer** [comment]
When someone else ran into this a couple of months ago, it turned out that they weren't getting `SRWLOCK` because they were using Windows XP, which is below the minimum of Windows Vista or Windows Server 2008. If you are in a similar situation, it would be best to work around this as you have done, I think, until RE2 can require C++17 someday.
