### ISSUE TITLE
Is substring extraction still slow? With std::string as well as StringPiece?

### ISSUE THREAD

**Issue by audaki** [google/re2#394]
So I was wondering about this comment from 13 years ago, which is not repeated on the Wiki pages. Is this comment still valid? And is it valid for std::string as well as StringPiece?

![image](https://user-images.githubusercontent.com/1321285/197839982-9999a02e-6f0e-4786-855d-2d9718c3c2e9.png)

**Comment by BurntSushi** [comment]
`std::string` vs `StringPiece` is irrelevant here. That comment is referring to the extra work needed to be done by the regex engine to discover the spans of capturing groups when compared to finding just the span of the overall match.

**Comment by junyer** [comment]
@rsc's [third article](https://swtch.com/~rsc/regexp/regexp3.html#step4) describes what happens under the hood in considerable detail; the gist is that, yes, the more capturing groups (including `$0`) that you want, the more work RE2 has to do. Generally speaking (because the specifics take us well into "it depends" territory), asking for at least `$1` entails running the DFA execution engine forwards to find the end of `$0` and then backwards to find the start of `$0` and **_then_** running another execution engine forwards to find `$1` et al. OTOH, a `true`/`false` result can be obtained just by running the DFA execution engine forwards.

Extracting to `std::string` involves a string copy whereas extracting to `re2::StringPiece` is approximately free (after the cost incurred during matching), so it's worth avoiding the former when possible.

**Comment by audaki** [comment]
@junyer Thank you for the article and explaining more in detail.

What I understood from the comment in re2.h was the following:
(Sub) String Extraction is Slow (BUT: Integer Extraction is NOT)

Maybe this was a misunderstanding and Integer Extraction is slow as well? As in all Capture Groups are slow?

**Comment by junyer** [comment]
Yeah, more capturing groups means more matching work and that's **_before_** the post-matching expense of extraction. (Also, numeric types are actually even more expensive because RE2 has to perform string copies in order to have NUL-terminated strings to feed to standard library functions such as `strtol(3)`, which can then be somewhat expensive themselves.)

Would it have been less confusing to say "submatch" instead of "substring" in this context?

**Comment by audaki** [comment]
@junyer Thanks for explaining and yes, that would've been a **lot** easier to understand! I was really confused why string extraction specifically was thought of as slow.

I think changing the wording to submatch might help more people understand the documentation.

**Comment by junyer** [comment]
Okay, I will look at rewording the comments in `re2.h` tonight.
