### ISSUE TITLE
Question on flatbuffer representation

### ISSUE THREAD

**Issue by snakelizzard** [google/re2#403]
If you are dealing with many regular expressions, it would be cool to be able to not waste time parsing. One option would be to load regular expression data structures from flatbufer. Tell me, please, do you plan to support such a feature? If not, please share your opinion on how difficult it will be to modify existing code. Thank you.

**Comment by junyer** [comment]
The first showstopper would be the adoption of any given format. RE2 won't take a dependency on FlatBuffers or Protobuf or anything else. There's a compact, human-readable format and that's the regular expression in textual form.

You could write a `Regexp::Walker<>` that exports the `Regexp` to some format and then write code that imports/reconstructs a `Regexp` from said format, but instantiating an `RE2` object given the `Regexp` isn't something that I would accept upstream because the `Regexp` interface is neither intended nor suitable for external (i.e. untrusted) consumption.

Also, parsing is distinct from compiling. Deriving the `Prog` (bytecode) from the `Regexp` (syntax tree) is a significant fraction of the overall cost, but the `Prog` contains implementation details – much more so than the `Regexp` – and so I would be even more unwilling to expose them because it would make them part of the interface contract, essentially, inasmuch as changing them would break users who were (implicitly) depending on them never changing.
