### ISSUE TITLE
Meaning of alternation in the wiki

### ISSUE THREAD

**Issue by tomaszdrab** [google/re2#408]
I came across the RE2 Wiki and found a sentence that I would correct. I would create a pull request to the wiki, but I've just discovered that it is unfortunately impossible on GitHub (and I haven't found any solution in [Contribute.md](https://github.com/google/re2/wiki/Contribute)).

Anyway, I would propose the following change in the [Syntax.md](https://github.com/google/re2/wiki/Syntax) file:
Instead
```
then <i>e</i><sub>1</sub><code>|</code><i>e</i><sub>2</sub> matches
<i>s</i>
or
<i>t</i>,
```
I would put
```
then <i>e</i><sub>1</sub><code>|</code><i>e</i><sub>2</sub> matches both
<i>s</i>
and
<i>t</i>,
```
.

I believe that it may help some future readers.

**Comment by junyer** [comment]
Thanks for the suggestion. Although I can understand why someone might consider "matches both _s_ and _t_" clearer, it would be too much of a departure from the typical "`|` means OR" lesson and somewhat problematic because AND is well defined, mathematically speaking, as the intersection of the sets of strings. Also, that introductory text was originally written by @rsc for https://swtch.com/~rsc/regexp/regexp1.html and adapted for that RE2 wiki page, so unless he agrees that both should be revised with regard to this matter, I don't want to make the latter deviate from the former.
