### ISSUE TITLE
Repetition values with leading zeros silently fail

### ISSUE THREAD

**Issue by 8ightfold** [google/re2#417]
I'm currently writing a parser, and to balance brackets I was using repetitions.
Doing ``expr{2}`` is ok, but trying to do ``expr{002}`` will make your code fail without any hint as to why.
A simplified version of what I was doing can be found here: https://regex101.com/r/3EM8HX/1 (this was not working with re2).

I spent hours trying to fix this "bug", and I feel like it should either give a warning, or be valid syntax.

**Comment by junyer** [comment]
RE2 silently treats an invalid counted repetition like a literal because, IIRC, that was what Perl did at the time. FWIW, Perl 5.36 carps about `x{02}`, for example, whereas Python 3.10 seemingly handles that like `x{2}`; without doing the archaeology, it's unknown to me when Perl's behaviour changed and whether Python's behaviour changed at all. However, at this point, RE2's behaviour isn't going to change.

Also, I would generally advise against using leading zeros because they may or may not indicate octal notation depending on the specific context.

Also also, I would generally recommend using pushdown automata, not finite automata, when parsing balanced brackets. (By which I mean parsing specifically; regular expressions are suitable when lexing, of course.)
