### ISSUE TITLE
I can't believe accents inside words are not supported. 

### ISSUE THREAD

**Issue by irg1008** [google/re2#433]
Using an accent inside \b does not work.

Do you know there are more languages out there a part from English right?

What's the alternative for example in spanish or french...

**Comment by junyer** [comment]
As per the [Syntax](https://github.com/google/re2/wiki/Syntax) wiki page, `\b` isn't Unicode-aware; for that matter, neither are `\d`, `\s` and `\w`. It's possible to simulate Unicode-aware word boundaries by using capturing groups: `(?:\A|[^\w\pL])(…)(?:[^\w\pL]|\z)` may suffice for your use case, for example, but note that you would have to use the first submatch (`$1`) rather than the match itself (`$0`).

**Comment by jorgefuertes** [comment]
Spanish is the most spoken language maybe after the Chinesse and it can't be \pL (any language). It should match the whole latin alphabet plus `áéíóúüñ` in both lower and upper cases.
