### ISSUE TITLE
how can I match compare operators > | >=

### ISSUE THREAD

**Issue by jiapengwen** [google/re2#435]
show you my code
``` c++

 //I have msg = "3>2 >=2"; I want to  regex > or >=, but re2 don't support (?!re), so I can't  distinguish > and >=;

 RE2 re(R"((>|>=))");
  std::cout << re.NumberOfCapturingGroups() << std::endl;
  absl::string_view found;
  while (RE2::FindAndConsume(&piece, re, &found)) {
    std::cout << found << std::endl;
  }
```
result
```shell
1
>
>
```

**Comment by junyer** [comment]
You have a couple of options. The first is to switch to POSIX leftmost-longest semantics and write `RE2 re(R"((>|>=))", RE2::POSIX);` instead. The second is to stick with PCRE leftmost semantics and write `RE2 re(R"((>=|>))");` instead. As currently written, matching `>=` never happens because matching `>` takes priority.

**Comment by jiapengwen** [comment]
thanks, it works well

**Comment by jiapengwen** [comment]
another question,  how can i get capture result
```c++
  {
    std::string input = "data_node(@x)+ @y";
    static RE2 re1{R"(data_node\(@[\s]*([a-zA-Z_0-9.]*))"};
    absl::string_view r1 = "data_node(\"$1\")"; // I want to replace use capture result to replace,  etc: x
    int n = RE2::GlobalReplace(&input, re1, r1);
    std::cout << n << "=" << input << std::endl;
  }
```

**Comment by junyer** [comment]
I'm guessing that you want `\1` rather than `$1`; see [this](https://github.com/google/re2/blob/1d465f627bab89cef3794a7ef89d712879d78d4a/re2/re2.h#L456-L460) documentation.

**Comment by jiapengwen** [comment]
worked, thanks,  this issue could closed
