### ISSUE TITLE
Compiling Unicode regex is significantly slower

### ISSUE THREAD

**Issue by matthill** [google/re2#46]
Not sure if this is expected, but I'm seeing significantly slower performance (~200x) when compiling unicode regex.  For example:

\pL\pL\pL\pN\pN -- Single regex compile Time: 8.09727ms.

versus:

[A-Za-z][A-Za-z][A-Za-z][0-9][0-9] -- Single regex compile Time: 0.035597ms

**Comment by junyer** [comment]
The compiled programs have 7103 instructions and 9 instructions, respectively, and this is simply because there are vastly more than 26 letters and 10 numbers in Unicode. You could conceivably experiment with more specific categories, but using Unicode only when necessary seems like the preferable option.
