### ISSUE TITLE
Cant get RE2::Consume to work

### ISSUE THREAD

**Issue by iAroc** [google/re2#481]
Hello

I tried now for a longer time, but i cant get RE2:Consume to work, even when i copy the example code etc.

i did build RE2 against following versions:
Abseil 20240116.1
RE2 2024-03-01

C++ standard is C+20

Here is an example test-code, that i think looks correct, but gives me back 0 matches:

```c++
    std::string  testString = "TEST TEST TEST TEST TEST";
    RE2::Options options;
    options.set_case_sensitive(true);

    RE2 pattern(R"(TEST.+?TEST)", options);

    std::vector<std::string> matches;
    re2::StringPiece         inputSp(testString);
    re2::StringPiece         match;

    while (RE2::Consume(&inputSp, pattern, &match)) {
        std::cout << "Match: " << match << '\n';
        matches.emplace_back(match.data());
    }
    std::cout << "Found " << matches.size() << " matches\n";
```

it should match 2x "TEST TEST", but it matches 0 times.

I also tried to have case_sensitive to false, or having the regex pattern directly in the RE::Consume call. no differences

Wrapping the testString in a ``absl::string_view`` instead of a ``re2::StringPiece`` makes no diff either

Can someone point out what im doing wrong?

**Comment by junyer** [comment]
As currently written, the code doesn't satisfy [this](https://github.com/google/re2/blob/27536b0d187fbce6cd6df693f64688c126dbb036/re2/re2.h#L436) condition because it's passing `&match` to `RE2::Consume()` when there are zero capturing groups in `pattern`. (Note that the parentheses in `R"(TEST.+?TEST)"` delimit the raw string literal and are **_not_** part of the pattern.)
