### ISSUE TITLE
libre2 library is taking more RAM size compare to -lboost_regex -lyaml_cpp  libraries linked to ua-parser/uap-cpp ua-parser/uap-core

### ISSUE THREAD

**Issue by KumaraVasantha** [google/re2#492]
Hi, 

Using below open source packages 

  ua-parser/uap-cpp	
   https://github.com/ua-parser/uap-cpp.git

 ua-parser/uap-core 	
   https://github.com/ua-parser/uap-core.git
   
RE2	 
https://github.com/google/re2/releases

When I linked libre2.so to the binary  to work newer uap-parser  RAM memory increased to 19MB to 20MB size. 

Need your help to reduce the RAM size while using libre2.so package 

# ls -lart /usr/lib/libre2.so*
lrwxrwxrwx    1 root     root           16 May  2  2024 /usr/lib/libre2.so.10 -> libre2.so.10.0.0
lrwxrwxrwx    1 root     root           16 May  2  2024 /usr/lib/libre2.so -> libre2.so.10.0.0
-rwxr-xr-x    1 root     root       471744 May  2  2024 /usr/lib/libre2.so.10.0.0
# 

 
# cat /proc/`pidof stainfod`/status | grep Vm*
VmPeak:	   36856 kB
**VmSize:	   36856 kB**     **Before it was 18MB increased to 36MB now** 
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   31092 kB
VmRSS:	   31092 kB
VmData:	   26108 kB
VmStk:	     136 kB
VmExe:	      44 kB
VmLib:	   10124 kB
VmPTE:	      42 kB
VmPMD:	       0 kB
VmSwap:	       0 kB

Please let me if I need to use any option to reduce the memory size 

Thanks,
Vasanth

**Comment by junyer** [comment]
The `VmSize` value in `/proc/<PID>/status` is the virtual memory size. It doesn't really mean much in terms of actual memory usage. You presumably ought to be looking at one or more of the values in `/proc/<PID>/smaps_rollup` instead.

However, it's unclear to me why two completely different regular expression libraries should have the same memory footprint. Still, if you can profile heap allocations performed by the application, you can hopefully quantify – and attribute – differences more precisely. It may be worth trying to set the [`max_mem`](https://github.com/google/re2/blob/2b354c6ad0d0479dcff68dab23fb0d1143a482c2/re2/re2.h#L624) option [here](https://github.com/ua-parser/uap-cpp/blob/05796295949028dbd0db4e476c143fd372c68fbd/internal/Pattern.cpp#L18-L21), for example, because the memory budget defaults to 8 MiB per `RE2` object, but there's no global "use less memory" configuration knob for RE2. (Just to be clear, there's also a CPU–RAM tradeoff that ought to be evaluated.)

**Comment by KumaraVasantha** [comment]
Hi, 

Thanks for the reply 

In re2.h file changed kDefaultMaxMem size to 8KB from 8MB as below,  then attached to the process. 


 657     // For now, make the default budget something close to Code Search.
 658     //static const int kDefaultMaxMem = 8<<20;  (8MB)
 
 
 659     static const int kDefaultMaxMem = 8<<10;    (8KB)
 
 
 Result : Now after above tweaking my application/process attached re2 library is taking  7MB  extra memory (before this changes process took 19MB to 20MB extra memory) 
 
 Please confirm , if I change the above parameter in re2.h file is there any impact of the library/process
 
 
 Thanks,
 Vasanth

**Comment by junyer** [comment]
Sorry, I'm confused. Could you please just explain the reason for reducing the default memory budget by three (3) orders of magnitude? Depending on the regular expression in question, reducing the default memory budget to 8 KiB may or may not cause compilation to fail due to memory budget exhaustion. Moreover, neither [`Pattern::assign()`](https://github.com/ua-parser/uap-cpp/blob/05796295949028dbd0db4e476c143fd372c68fbd/internal/Pattern.cpp#L14) nor [`Pattern::match()`](https://github.com/ua-parser/uap-cpp/blob/05796295949028dbd0db4e476c143fd372c68fbd/internal/Pattern.cpp#L29) checks whether compilation failed, so when it **_is_** the case that compilation failed, matching will fail and immediately return `false`, which is a false negative iff matching should have returned `true` for the input string in question. (One can only hope that your application has sufficient test coverage to catch that.)
