### ISSUE TITLE
Could you improve on `[a-q][^u-z]{13}x` regex ?

### ISSUE THREAD

**Issue by crquan** [google/re2#63]
Can't understand why re2 runs slower in this particular regex? although in most cases re2 runs the fastest, but this particular one prevented use drop in use of re2 as replacement of language default implementation.

http://sljit.sourceforge.net/regex_perf.html

```
[a-q][^u-z]{13}x	746 ms	2741 ms	1928 ms	61 ms	3512 ms	2 ms
```

**Comment by junyer** [comment]
The regular expression causes an exponential blowup in DFA states, which the following table illustrates:

regular expression | DFA states
---|---
`[a-q][^u-z]{0}x` | 4
`[a-q][^u-z]{1}x` | 6
`[a-q][^u-z]{2}x` | 10
`[a-q][^u-z]{3}x` | 18
`[a-q][^u-z]{4}x` | 34
`[a-q][^u-z]{5}x` | 66
`[a-q][^u-z]{6}x` | 130
`[a-q][^u-z]{7}x` | 258
`[a-q][^u-z]{8}x` | 514
`[a-q][^u-z]{9}x` | 1026
`[a-q][^u-z]{10}x` | 2050
`[a-q][^u-z]{11}x` | 4098
`[a-q][^u-z]{12}x` | 8194
`[a-q][^u-z]{13}x` | 16386
`[a-q][^u-z]{14}x` | 32770
`[a-q][^u-z]{15}x` | 65538

The effect is that RE2 spends too much time populating the DFA state cache and too little time benefitting from it.

Note that this is a problem with the regular expression, not with RE2. However, I suppose that the regular expression was chosen quite deliberately. :)

**Comment by crquan** [comment]
while is there a solution to fix this slow processing? @junyer could you re-open?

**Comment by junyer** [comment]
I imagine that the much better performance of other engines is due to their looking for the `x` before matching the `[a-q][^u-z]{13}`. It's a neat trick, but antithetical to the principles underlying RE2. :/

**Comment by crquan** [comment]
but does there exist a solution to be generally faster than default PCRE ? as it is mentioned in Russ's paper, is re2's goal to be that one to be faster in all cases?
https://swtch.com/~rsc/regexp/regexp1.html

**Comment by junyer** [comment]
It is a goal to be generally faster – by virtue of not backtracking – and I believe that RE2 meets that goal. Indeed, you said "in most cases re2 runs the fastest" in your initial comment.

It is not a goal to be faster in all cases. RE2 guarantees linear-time performance, but the linear-time constant varies depending on the overhead entailed by safe handling of the regular expression. In a sense, RE2 is pessimistic whereas backtracking engines are optimistic, so it can be outperformed in various situations. Bear in mind that this is because RE2 has an explicit goal of being able to handle regular expressions from untrusted users without risk.

(Ping, @rsc.)
